name: CodeGuru Analysis and Upload Results

# Manual trigger with workflow_dispatch
on:
  workflow_dispatch:

jobs:
  codeguru:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read

    steps:
      # Step 1: Check out the repository code
      - name: Checkout Code
        uses: actions/checkout@v3

      # Step 2: Configure AWS Credentials for CodeGuru
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      # Step 3: Set up Node.js environment (if needed)
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      # Step 4: Trigger CodeGuru Reviewer to analyze the repository
      - name: Trigger CodeGuru Review
        run: |
          aws codeguru-reviewer create-code-review \
            --name CodeGuruReview_${{ github.sha }} \
            --repository-association-arn arn:aws:codeguru-reviewer:us-east-1:008971672094:association:4b8922f2-0794-4a26-873e-48efdb9bfd49 \
            --type '{"RepositoryAnalysis": {"RepositoryHead": {"BranchName": "dev"}}}'

      # Step 5: Wait for CodeGuru Review to Complete
      - name: Wait for CodeGuru Review to Complete
        run: |
          echo "Waiting for CodeGuru review to complete..."
          sleep 140

      # Step 6: Get the Most Recent CodeGuru Review ARN
      - name: Get the Most Recent CodeGuru Review ARN
        id: get_arn
        run: |
          REVIEW_ARN=$(aws codeguru-reviewer list-code-reviews \
            --query 'codeReviews[?state==`Completed`].codeReviewArn' \
            --output text | head -n 1)
          
          if [ -z "$REVIEW_ARN" ]; then
            echo "No CodeGuru review found."
            exit 1
          fi

          echo "REVIEW_ARN=$REVIEW_ARN" >> $GITHUB_ENV

      # Step 7: Fetch the CodeGuru Results
      - name: Fetch CodeGuru Results
        run: |
          if [ -z "${{ env.REVIEW_ARN }}" ]; then
            echo "No CodeGuru review ARN


